### ISSUE TITLE
dep on counterparty-lib 9.49.3 even though 9.49.4 is avail, errs on existing counterparty-server

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterparty-cli#10]
* Win 7 x64
* Python 3.4.2 x32

* counterparty-cli depends on the old version of counterparty-lib (9.49.3)
https://github.com/CounterpartyXCP/counterparty-cli/blob/develop/setup.py#L17 (L21, L46)
* counterparty-cli can't handle existing `counterparty-server` file
```
Installing collected packages: counterparty-cli, counterparty-lib
  Running setup.py install for counterparty-cli

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\rippler_AD~1\AppData\Local\Temp\pip_build_rippler\counterparty-cli\setup.py", line 174, in <module>
        os.makedirs(new_server_appdir)
      File "C:\Python34\lib\os.py", line 237, in makedirs
        mkdir(name, mode)
    FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\rippler_ADMIN\\AppData\\Roaming\\Counterparty\\counterparty-server'
    Complete output from command C:\Python34\python.exe -c "import setuptools;__file__='C:\\Users\\rippler_AD~1\\AppData\\Local\\Temp\\pip_build_rippler
nterparty-cli\\setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\rippler_AD~1\AppData
l\Temp\pip-5qoiuv8b-record\install-record.txt --single-version-externally-managed:
    running install

running build

running build_py

creating build

creating build\lib

creating build\lib\counterpartycli

copying counterpartycli\client.py -> build\lib\counterpartycli

copying counterpartycli\server.py -> build\lib\counterpartycli

copying counterpartycli\util.py -> build\lib\counterpartycli

copying counterpartycli\__init__.py -> build\lib\counterpartycli

creating build\lib\counterpartycli\wallet

copying counterpartycli\wallet\bitcoincore.py -> build\lib\counterpartycli\wallet

copying counterpartycli\wallet\__init__.py -> build\lib\counterpartycli\wallet

running build_scripts

creating build\scripts-3.4

copying and adjusting bin\counterparty-client -> build\scripts-3.4

copying and adjusting bin\counterparty-server -> build\scripts-3.4

running install_lib

creating C:\Python34\Lib\site-packages\counterpartycli

copying build\lib\counterpartycli\client.py -> C:\Python34\Lib\site-packages\counterpartycli

copying build\lib\counterpartycli\server.py -> C:\Python34\Lib\site-packages\counterpartycli

copying build\lib\counterpartycli\util.py -> C:\Python34\Lib\site-packages\counterpartycli

creating C:\Python34\Lib\site-packages\counterpartycli\wallet

copying build\lib\counterpartycli\wallet\bitcoincore.py -> C:\Python34\Lib\site-packages\counterpartycli\wallet

copying build\lib\counterpartycli\wallet\__init__.py -> C:\Python34\Lib\site-packages\counterpartycli\wallet

copying build\lib\counterpartycli\__init__.py -> C:\Python34\Lib\site-packages\counterpartycli

byte-compiling C:\Python34\Lib\site-packages\counterpartycli\client.py to client.cpython-34.pyc

byte-compiling C:\Python34\Lib\site-packages\counterpartycli\server.py to server.cpython-34.pyc

byte-compiling C:\Python34\Lib\site-packages\counterpartycli\util.py to util.cpython-34.pyc

byte-compiling C:\Python34\Lib\site-packages\counterpartycli\wallet\bitcoincore.py to bitcoincore.cpython-34.pyc

byte-compiling C:\Python34\Lib\site-packages\counterpartycli\wallet\__init__.py to __init__.cpython-34.pyc

byte-compiling C:\Python34\Lib\site-packages\counterpartycli\__init__.py to __init__.cpython-34.pyc

running install_egg_info

running egg_info

writing requirements to counterparty_cli.egg-info\requires.txt

writing top-level names to counterparty_cli.egg-info\top_level.txt
```

* If I uninstall `counterparty-lib` then `counterparty-cli` installs `counterparty-lib` 9.49.3
* A workaround is to install `counterparty-cli` first, then upgrade `counterparty-lib` to 9.49.4

**Comment by ouziel-slama** [comment]
I don't think it's a bug. Each `counterparty-cli` version depends on a particular `counteparty-lib` version.
For now, and until the the release of `v9.49.4`, `counterparty-cli` depends on the `develop` branch of  `counterparty-lib`. 
So if you have a too recent `counterparty-lib` version installed is normal to get an error.

**Comment by rippler** [comment]
Okay. Is `counterparty-cli` supposed to be able to install now or does that mean `counterparty-lib` 9.49.3 is broken?  
If I just run `sudo pip3 install counterparty-cli`, it fails to install.

```
..
Copying counterparty_cli.egg-info to /usr/local/lib/python3.4/dist-packages/counterparty_cli-1.0.0.egg-info

running install_scripts

copying build/scripts-3.4/counterparty-server -> /usr/local/bin

copying build/scripts-3.4/counterparty-client -> /usr/local/bin

changing mode of /usr/local/bin/counterparty-server to 755

changing mode of /usr/local/bin/counterparty-client to 755

writing list of installed files to '/tmp/pip-5f4f0dcv-record/install-record.txt'

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip_build_root/counterparty-cli/setup.py", line 84, in <module>

    from counterpartylib.lib import config, util

ImportError: No module named 'counterpartylib'

----------------------------------------
Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/counterparty-cli/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-5f4f0dcv-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/counterparty-cli
Storing debug log for failure in /home/rippler/.pip/pip.log

```

**Comment by ouziel-slama** [comment]
Until the release of `v1.0.0` and `v9.49.4`, just do: 

`pip install https://github.com/CounterpartyXCP/counterparty-cli/archive/develop.zip`
