### ISSUE TITLE
counterparty-client unhandled exception

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterparty-cli#11]
`counterparty-server` v9.49.4 handles it, but `counterparty-cli` 1.0.0 does not.

```
rippler@ubuntu:/usr/local/lib/python3.4/dist-packages$ counterparty-client -V
counterparty-client v1.0.0

rippler@ubuntu:/usr/local/lib/python3.4/dist-packages$ counterparty-server
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 12, in <module>
    server.main()
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/server.py", line 172, in main
    broadcast_tx_mainnet=broadcast_tx_mainnet)
  File "/usr/local/lib/python3.4/dist-packages/counterpartylib/server.py", line 155, in initialise
    raise ConfigurationError('backend RPC password not set. (Use configuration file or --backend-password=PASSWORD)')
counterpartylib.server.ConfigurationError: backend RPC password not set. (Use configuration file or --backend-password=PASSWORD)

rippler@ubuntu:/usr/local/lib/python3.4/dist-packages$ counterparty-client
[INFO] Running v1.0.0 of counterparty-client.
[ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-client", line 12, in <module>
    client.main()
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/client.py", line 684, in main
    wallet_ssl=args.wallet_ssl, wallet_ssl_verify=args.wallet_ssl_verify)
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/client.py", line 337, in set_options
    raise ConfigurationError('counterparty RPC password not set. (Use configuration file or --counterparty-rpc-password=PASSWORD)')
counterpartycli.client.ConfigurationError: counterparty RPC password not set. (Use configuration file or --counterparty-rpc-password=PASSWORD)

```

**Comment by adamkrellenstein** [comment]
The problem isn't that the exception is unhandled, but that the configuration is incomplete.
