### ISSUE TITLE
Missing python-bitcoinlib, 

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-cli#115]
First I installed counterparty-lib with `sudo pip install counterparty-lib==9.55.4`.

Then counterparty-cli failed: 

```
   Installing counterparty-server script to /usr/local/bin
    writing list of installed files to '/tmp/pip-n6hgxfpd-record/install-record.txt'
    running generate_configuration_files
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-waup_l9f/counterparty-cli/setup.py", line 125, in <module>
        setup(**setup_options)
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-waup_l9f/counterparty-cli/setup.py", line 33, in run
        self.run_command('generate_configuration_files')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-waup_l9f/counterparty-cli/setup.py", line 20, in run
        generate_config_files()
      File "/tmp/pip-build-waup_l9f/counterparty-cli/counterpartycli/setup.py", line 142, in generate_config_files
        from counterpartycli.server import CONFIG_ARGS as SERVER_CONFIG_ARGS
      File "/tmp/pip-build-waup_l9f/counterparty-cli/counterpartycli/server.py", line 9, in <module>
        from counterpartylib.lib import log
      File "/usr/local/lib/python3.5/dist-packages/counterpartylib/lib/log.py", line 16, in <module>
        from counterpartylib.lib import util
      File "/usr/local/lib/python3.5/dist-packages/counterpartylib/lib/util.py", line 19, in <module>
        import bitcoin as bitcoinlib
    ImportError: No module named 'bitcoin'

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-waup_l9f/counterparty-cli/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-n6hgxfpd-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-waup_l9f/counterparty-cli/
```

I installed bitcoinlib, but it's a wrong one (https://github.com/1200wd/bitcoinlib):

```
Successfully installed bitcoinlib-0.3.0.25 ecdsa-0.13 pbkdf2-1.3 scrypt-0.8.0 sqlalchemy-1.1.14
```

I had to manually install python-bitcoinlib with pip.

Now, the weird thing is util.py Line 19 doesn't have `import bitcoin as bitcoinlib`.
But I found such a line here:
https://github.com/CounterpartyXCP/counterparty-cli/blob/1.1.2/counterpartycli/messages.py#L15

**Comment by chiguireitor** [comment]
Is this already solved? devon's change that included a specific commit of this lib seems to do the right thing
