### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by ek1977** [CounterpartyXCP/counterparty-cli#123]
I have been experiencing the following error for the past few days.  I'm running an up-to-date version of the cli code.

[2019-02-16 14:56:40][ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 11, in <module>
    load_entry_point('counterparty-cli==1.1.4', 'console_scripts', 'counterparty-server')()
  File "/usr/local/lib/python3.6/dist-packages/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/usr/local/lib/python3.6/dist-packages/counterpartycli/server.py", line 164, in main
    server.start_all(db)
  File "/usr/local/lib/python3.6/dist-packages/counterparty_lib-9.56.0-py3.6.egg/counterpartylib/server.py", line 466, in start_all
    blocks.follow(db)
  File "/usr/local/lib/python3.6/dist-packages/counterparty_lib-9.56.0-py3.6.egg/counterpartylib/lib/blocks.py", line 1248, in follow
    check.asset_conservation(db)
  File "/usr/local/lib/python3.6/dist-packages/counterparty_lib-9.56.0-py3.6.egg/counterpartylib/lib/check.py", line 160, in asset_conservation
    raise SanityError('{} {} issued \u2260 {} {} held'.format(util.value_out(db, asset_issued, asset), asset, util.value_out(db, asset_held, asset), asset))
counterpartylib.lib.check.SanityError: 2615772.9267785 XCP issued \u2260 2614974.6192385 XCP held
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 995, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2260' in position 985: ordinal not in range(128)
Call stack:
  File "/usr/local/lib/python3.6/dist-packages/counterparty_lib-9.56.0-py3.6.egg/counterpartylib/server.py", line 180, in handle_exception
    logger.error("Unhandled Exception", exc_info=(exc_type, exc_value, exc_traceback))
Message: 'Unhandled Exception'
Arguments: ()

**Comment by chiguireitor** [comment]
Please, update to latest master, this issued was a hotfix in the last commit.
