### ISSUE TITLE
9.49.4rc4: First block in database is not block 310000

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterparty-cli#15]
DB was created with `counterpartyd` 9.49.3.  Even if the DB directory is empty, the error hapens. Reparse of the existing DB exits with the same error.
```
[INFO] Starting API Server.←[0m
←[31m[ERROR] Unhandled Exception←[0m
Traceback (most recent call last):
  File "C:\Python34\Scripts\counterparty-server-script.py", line 9, in <module>
    load_entry_point('counterparty-cli==1.0.0rc4', 'console_scripts', 'counterparty-server')()
  File "C:\Python34\lib\site-packages\counterpartycli\__init__.py", line 14, in server_main
    server.main()
  File "C:\Python34\lib\site-packages\counterpartycli\server.py", line 170, in main
    server.start_all(db)
  File "C:\Python34\lib\site-packages\counterpartylib\server.py", line 351, in start_all
    blocks.follow(db)
  File "C:\Python34\lib\site-packages\counterpartylib\lib\blocks.py", line 867, in follow
    initialise(db)
  File "C:\Python34\lib\site-packages\counterpartylib\lib\blocks.py", line 202, in initialise
    raise exceptions.DatabaseError('First block in database is not block {}.'.format(config.BLOCK_FIRST))
counterpartylib.lib.exceptions.DatabaseError: First block in database is not block 310000.←[0m
←[31m[ERROR] Unhandled Exception←[0m
Traceback (most recent call last):
  File "C:\Python34\Scripts\counterparty-server-script.py", line 9, in <module>
    load_entry_point('counterparty-cli==1.0.0rc4', 'console_scripts', 'counterparty-server')()
  File "C:\Python34\lib\site-packages\counterpartycli\__init__.py", line 14, in server_main
    server.main()
  File "C:\Python34\lib\site-packages\counterpartycli\server.py", line 170, in main
    server.start_all(db)
  File "C:\Python34\lib\site-packages\counterpartylib\server.py", line 351, in start_all
    blocks.follow(db)
  File "C:\Python34\lib\site-packages\counterpartylib\lib\blocks.py", line 867, in follow
    initialise(db)
  File "C:\Python34\lib\site-packages\counterpartylib\lib\blocks.py", line 202, in initialise
    raise exceptions.DatabaseError('First block in database is not block {}.'.format(config.BLOCK_FIRST))
counterpartylib.lib.exceptions.DatabaseError: First block in database is not block 310000.←[0m

```
Testnet config file:

```
[Default]
backend-name = addrindex
backend-user = rpc
backend-password = testnet
rpc-host = localhost
rpc-user = rpc
rpc-password = testnet
testnet = 1
data-dir = C:\blockchain\counterparty-testnet
config-file = C:\blockchain\TESTNET.counterpartyd.conf
```

**Comment by ouziel-slama** [comment]
Seems you server don't use the correct database.
There is no more `data-dir` parameter. You can use `database-file` instead.

**Comment by rippler** [comment]
I tried that, but it didn't work because the explanation is not clear enough. I'll submit a PR.
