### ISSUE TITLE
v1.0.0rc3 upgrade: UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 5639

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterparty-cli#16]
* Windows 7
* Python 3.4.2
* counterparty-cli 1.0.0rc3

Running `pip3 install --pre --upgrade counterparty-cli`:

```
C:\Windows\System32>pip3 install --pre --upgrade counterparty-cli
Downloading/unpacking counterparty-cli from https://pypi.python.org/packages/source/c/counterparty-cli/counterparty-cli-1.0.0rc5.tar.gz#md5=569c292c58
1c63c3d9c72b387be0d9d4
  Downloading counterparty-cli-1.0.0rc5.tar.gz
  Running setup.py egg_info for package counterparty-cli
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 5639: character maps to <undefined>
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode

    return codecs.charmap_decode(input,self.errors,decoding_table)[0]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 5639: character maps to <undefined>

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in C:\Users\hal_AD~1\AppData\Local\Temp\pip_build_sean\counterparty-cli
Storing complete log in C:\Users\hal_ADMIN\pip\pip.log
```

**Comment by adamkrellenstein** [comment]
I use a lot of Unicode characters when I write, e.g., logging.

**Comment by adamkrellenstein** [comment]
What's the problematic character?

**Comment by rippler** [comment]
It's not defined (C:\Python34\lib\encodings\cp1252.py, L292):
`'\ufffe'   #  0x90 -> UNDEFINED`

**Comment by adamkrellenstein** [comment]
@rippler, try running `setup.py install` with this commit: https://github.com/CounterpartyXCP/counterparty-cli/commit/4dc29dba3d4143b838a0d5206f6f0a758fc06e97

**Comment by rippler** [comment]
Installs fine!
