### ISSUE TITLE
counterparty-cli: local variable 'btc_out' referenced before assignment, can with "--unconfirmed"

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterparty-cli#2]
_From @rippler on January 9, 2015 18:15_

I get this when I try to open a bet from a testnet address.
```
[INFO] Running v9.49.3 of counterpartyd.←[0m
[INFO] Connecting to database.←[0m
←[31m[ERROR] Unhandled Exception←[0m
Traceback (most recent call last):
  File "c:\counterpartyd_build\dist\counterpartyd\counterparty-cli.py", line 869
, in <module> args.unsigned)
  File "c:\counterpartyd_build\dist\counterpartyd\counterparty-cli.py", line 232
, in cli unsigned_tx_hex = util.api(method, params)
  File "c:\counterpartyd_build\dist\counterpartyd\lib\util.py", line 69, in api
    raise RPCError('{}'.format(response_json['error']))
lib.util.RPCError: {'message': 'Server error', 'code': -32000, 'data': {'message
': "local variable 'btc_out' referenced before assignment", 'args': ["local vari
able 'btc_out' referenced before assignment"], 'type': 'UnboundLocalError'}}←[0m
```
Then I add `--unconfirmed` and it goes through right away.

_Copied from original issue: CounterpartyXCP/counterpartyd#610_

**Comment by rippler** [comment]
Unfortunately I can't remember which address I was using, but this may be related to the other bug whereby bets could be made from an address even if XCP balance was 0.

**Comment by adamkrellenstein** [comment]
@rippler, no, that's implausible.

**Comment by ouziel-slama** [comment]
should be fixed with: https://github.com/CounterpartyXCP/counterpartyd/commit/33e527b8edee5bf915ffba0b0b03e5795c260913

**Comment by rippler** [comment]
I just got this on counterwallet.io while trying to place an order on the DEx:

```
Sorry, we got an error when trying to do the requested action: 'JSON-RPC Error:
Type: Server error
Code: -32000
Message: local variable 'btc_out' referenced before assignment
' (API method: create_order).
If this persists, please click on the question mark button on the top right-hand corner of the screen for support options.
```

**Comment by adamkrellenstein** [comment]
@rippler, that Counterwallet server probably just isn't using the latest version.

**Comment by rippler** [comment]
@ouziel-slama do you know if counterwallet.io is using the latest version? I got the same error on it today.
