### ISSUE TITLE
'module' object has no attribute 'packages'

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterparty-cli#23]
I first installed Fed Node and noticed counterparty-client is not installed. When I installed counterparty-cli, it threw this error:
```
Using /usr/lib/python3/dist-packages
Finished processing dependencies for counterparty-cli==1.0.0
writing list of installed files to '/tmp/pip-lt8uw0eq-record/install-record.txt'
running generate_configuration_files
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip_build_root/counterparty-cli/setup.py", line 116, in <module>
    setup(**setup_options)
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/tmp/pip_build_root/counterparty-cli/setup.py", line 28, in run
    self.run_command('generate_configuration_files')
  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/tmp/pip_build_root/counterparty-cli/setup.py", line 21, in run
    generate_config_files()
  File "/tmp/pip_build_root/counterparty-cli/counterpartycli/setup.py", line 140, in generate_config_files
    from counterpartycli.server import CONFIG_ARGS as SERVER_CONFIG_ARGS
  File "/tmp/pip_build_root/counterparty-cli/counterpartycli/server.py", line 10, in <module>
    log.set_up(logger)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.49.4-py3.4.egg/counterpartylib/lib/log.py", line 55, in set_up
    requests.packages.urllib3.disable_warnings()
AttributeError: 'module' object has no attribute 'packages'
----------------------------------------
Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/counterparty-cli/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-lt8uw0eq-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/counterparty-cli
Storing debug log for failure in /home/rippler/.pip/pip.log

```
After I listed pip3 packages and it's there, but when I run it, it doesn't run.

```
counterparty-cli (1.0.0)
counterparty-lib (9.49.4)
```
Here's what I get.

```
 counterparty-client
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-client", line 9, in <module>
    load_entry_point('counterparty-cli==1.0.0', 'console_scripts', 'counterparty-client')()
  File "/usr/local/lib/python3.4/dist-packages/counterparty_cli-1.0.0-py3.4.egg/counterpartycli/__init__.py", line 11, in client_main
    from counterpartycli import client
  File "/usr/local/lib/python3.4/dist-packages/counterparty_cli-1.0.0-py3.4.egg/counterpartycli/client.py", line 20, in <module>
    from counterpartycli import util
  File "/usr/local/lib/python3.4/dist-packages/counterparty_cli-1.0.0-py3.4.egg/counterpartycli/util.py", line 26, in <module>
    log.set_up(logger)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.49.4-py3.4.egg/counterpartylib/lib/log.py", line 55, in set_up
    requests.packages.urllib3.disable_warnings()
AttributeError: 'module' object has no attribute 'packages'
```

I tried with requests v2.3.0 as well, same thing. 
Similar issue:
https://lists.debian.org/debian-python/2014/11/msg00021.html

**Comment by ouziel-slama** [comment]
hum.. seems you have to install a more recent version, try please with the latest.

**Comment by ouziel-slama** [comment]
The best I think is that you try the new install procedure described in the develop branch:

```
$ git clone https://github.com/CounterpartyXCP/counterparty-cli.git
$ cd counterparty-cli
$ pip3 install -r requirements.txt
$ python3 setup.py install
```
it works well on a Travis box.

**Comment by rippler** [comment]
Which `requirements.txt` is that?

**Comment by rippler** [comment]
@ouziel-slama is that to say since now we don't enforce particular versions of 3rd party pip packages, one has to find one that works? 
Shouldn't we have a list of what works published somewhere for reference? Otherwise, if one should simply install the latest stable, we could state that as well.

**Comment by ouziel-slama** [comment]
yes, the content of `requirements.txt` means "This package was tested and works well with versions listed in https://pypi.python.org/simple/"

**Comment by rippler** [comment]
I got that, but I was wondering where you got that `requirements.txt` from :-) Now I see you mentioned `develop`... Before I was simply following the steps you provided (which clones from `master`) :-).
The first line should be:
`git clone https://github.com/CounterpartyXCP/counterparty-cli.git --branch develop`

**Comment by rippler** [comment]
I still get the same error even with a develop edition and using the manual setup procedure (all my requirements are already satisfied).

```
writing manifest file 'counterparty_cli.egg-info/SOURCES.txt'
Copying counterparty_cli.egg-info to /usr/local/lib/python3.4/dist-packages/counterparty_cli-1.0.0.egg-info
running install_scripts
Installing counterparty-client script to /usr/local/bin
Installing counterparty-server script to /usr/local/bin
running generate_configuration_files
Traceback (most recent call last):
  File "setup.py", line 126, in <module>
    setup(**setup_options)
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 34, in run
    self.run_command('generate_configuration_files')
  File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 21, in run
    generate_config_files()
  File "/home/rippler/counterparty-cli/counterpartycli/setup.py", line 140, in generate_config_files
    from counterpartycli.server import CONFIG_ARGS as SERVER_CONFIG_ARGS
  File "/home/rippler/counterparty-cli/counterpartycli/server.py", line 10, in <module>
    log.set_up(logger)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.49.4-py3.4.egg/counterpartylib/lib/log.py", line 55, in set_up
    requests.packages.urllib3.disable_warnings()
AttributeError: 'module' object has no attribute 'packages'
```

PIP list:

```
appdirs (1.4.0)
Warning: cannot find svn location for apsw==3.8.2-r1
apsw (3.8.2-r1)
certifi (14.05.14)
chardet (2.0.1)
colorama (0.2.5)
colorlog (2.6.0)
command-not-found (0.3)
counterparty-cli (1.0.0, /home/rippler/counterparty-cli)
counterparty-lib (9.49.4)
cov-core (1.15.0)
coverage (3.7.1)
docutils (0.11)
Flask (0.10.1)
Flask-HTTPAuth (2.3.0)
html5lib (0.999)
itsdangerous (0.24)
Jinja2 (2.7.2)
json-rpc (1.8.1)
language-selector (0.1)
MarkupSafe (0.18)
Pillow (2.3.0)
pip (1.5.4)
prettytable (0.7.2)
py (1.4.26)
pycoin (0.52)
pycrypto (2.6.1)
pycurl (7.19.3)
Pygments (1.6)
pygobject (3.12.0)
pysha3 (0.3)
pytest (2.6.4)
pytest-cov (1.8.1)
python-apt (0.9.3.5ubuntu1)
python-bitcoinlib (0.2.1)
python-dateutil (2.4.0)
pyzmq (14.0.1)
requests (2.5.1)
roman (2.0.0)
setuptools (3.3)
six (1.5.2)
Sphinx (1.2.2)
tendo (0.2.7)
tornado (4.1)
ufw (0.34-rc-0ubuntu2)
urllib3 (1.7.1)
Werkzeug (0.10.1)
```

**Comment by rippler** [comment]
Now I tested again with a clean U14.04 server and it worked. 

Went back to the Fed Node to see what went wrong there. I can't tell for sure, maybe I didn't run `pip3 install -r requirements.txt` as sudoer.
Now when I try there, I start with this:
```
Warning: cannot find svn location for apsw==3.8.2-r1
apsw (3.8.2-r1)
chardet (2.0.1)
colorama (0.2.5)
command-not-found (0.3)
docutils (0.11)
html5lib (0.999)
Jinja2 (2.7.2)
language-selector (0.1)
MarkupSafe (0.18)
Pillow (2.3.0)
pip (1.5.4)
pycurl (7.19.3)
Pygments (1.6)
pygobject (3.12.0)
python-apt (0.9.3.5ubuntu1)
pyzmq (14.0.1)
requests (2.2.1)
roman (2.0.0)
setuptools (3.3)
six (1.5.2)
Sphinx (1.2.2)
ufw (0.34-rc-0ubuntu2)
urllib3 (1.7.1)
```
After running `pip3 install -r requirements.txt`:
```
  File "<string>", line 17, in <module>
  File "/home/rippler/counterparty-cli/setup.py", line 126, in <module>
    setup(**setup_options)
  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 239, in __init__
    self.fetch_build_eggs(attrs.pop('setup_requires'))
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs
    replace_conflicting=True
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 620, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 852, in best_match
    dist = working_set.find(req)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 503, in find
    raise VersionConflict(dist,req)     # XXX add more info
pkg_resources.VersionConflict: (requests 2.2.1 (/usr/lib/python3/dist-packages), Requirement.parse('requests>=2.3.0'))

----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_rippler...
Command python setup.py egg_info failed with error code 1 in /home/rippler/counterparty-cli
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1145, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python3/dist-packages/pip/req.py", line 325, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python3/dist-packages/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command python setup.py egg_info failed with error code 1 in /home/rippler/counterparty-cli
```
The approach does work, but `requests` must be first uninstalled.

**Comment by ouziel-slama** [comment]
Yes, it's the normal behaviour of `pip`.. if the package is already installed it's not upgraded.
did you try with `pip install --upgrade -r requirements.txt` ?
I will make more tests, and eventually add version number in `requirements.txt`.

**Comment by rippler** [comment]
I haven't tried that yet, been quite busy with Fed Node Build script (I was trying to figure out whether `counterparty-cli` was installed by Fed Node script (https://github.com/CounterpartyXCP/federatednode_build/issues/216)).

**Comment by rippler** [comment]
Okay, to summarize a workaround from the current `develop` branch:
```
git clone https://github.com/CounterpartyXCP/counterparty-cli.git --branch develop
cd counterparty-cli
sudo pip3 install --upgrade -r requirements.txt
sudo python3 setup.py install 
```
