### ISSUE TITLE
counterparty-cli -h|--help doesn't work

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterparty-cli#24]
It complains about missing config files.

```
C:\Python34>counterparty-client -h
←[31m[ERROR] Unhandled Exception←[0m
Traceback (most recent call last):
  File "C:\Python34\Scripts\counterparty-client-script.py", line 9, in <module>
    load_entry_point('counterparty-cli==1.0.0', 'console_scripts', 'counterparty-client')()
  File "C:\Python34\lib\site-packages\counterparty_cli-1.0.0-py3.4.egg\counterpartycli\__init__.py", line 12, in client_main
    client.main()
  File "C:\Python34\lib\site-packages\counterparty_cli-1.0.0-py3.4.egg\counterpartycli\client.py", line 655, in main
    wallet_ssl=args.wallet_ssl, wallet_ssl_verify=args.wallet_ssl_verify)
  File "C:\Python34\lib\site-packages\counterparty_cli-1.0.0-py3.4.egg\counterpartycli\client.py", line 421, in set_options
    raise ConfigurationError('wallet RPC password not set. (Use configuration file or --wallet-password=PASSWORD)')
counterpartycli.client.ConfigurationError: wallet RPC password not set. (Use configuration file or --wallet-password=PASSWORD)←[0m
```

**Comment by ouziel-slama** [comment]
fixed here: https://github.com/CounterpartyXCP/counterparty-cli/commit/47b9c283ba5c2930321584e27f07061a0f64b7fd
