### ISSUE TITLE
Issuance: unexpected keyword argument 'divisible'

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterparty-cli#31]
* It seems `divisible` should default to `True`, but here it can't work without it being set
* In `issuance --help` it is not clear what are the options for `divisible` (it seems the lack of `--divisible` would mean undivisible, but in practice it doesn't). Can this be clarified in online help?
```
counterparty-client.exe --config-file TESTNET-counterparty-client.conf issuance --source mkZ6ECVZYtTE6iGZ6wvBfkw49KAvsGhCM --quantity XCPRULEZ --description TESTASSET --asset XCPRULEZ

←[31m[ERROR] Unhandled Exception←[0m
Traceback (most recent call last):
  File "c:\Python34\Scripts\counterparty-client-script.py", line 9, in <module>
    load_entry_point('counterparty-cli==1.0.0', 'console_scripts', 'counterparty-client')()
  File "C:\Python34\lib\site-packages\counterparty_cli-1.0.0-py3.4.egg\counterpartycli\__init__.py", line 12, in client_main
    client.main()
  File "C:\Python34\lib\site-packages\counterparty_cli-1.0.0-py3.4.egg\counterpartycli\client.py", line 727, in main
    quantity = util.value_in(args.quantity, None, divisible=args.divisible)
TypeError: value_in() got an unexpected keyword argument 'divisible'←[0m
```

**Comment by jdogresorg** [comment]
I can confirm I am seeing the same behavior

# Issuance WITHOUT divisible specified... returns error
xcp@chain:~/.config/counterparty$ counterparty-cli issuance --source 1AssetiB9oec9pmbTThvCLFqBPcLSaQGjB --quantity=0 --asset TESTINGSTUFF --description="test"
[ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-cli", line 9, in <module>
    load_entry_point('counterparty-cli==1.0.0', 'console_scripts', 'counterparty-client')()
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterparty_cli-1.0.0-py3.4.egg/counterpartycli/__init__.py", line 12, in client_main
    client.main()
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterparty_cli-1.0.0-py3.4.egg/counterpartycli/client.py", line 727, in main
    quantity = util.value_in(args.quantity, None, divisible=args.divisible)
TypeError: value_in() got an unexpected keyword argument 'divisible'

# Issuance WITH divisible specified... returns error
xcp@chain:~/.config/counterparty$ counterparty-cli issuance --source 1AssetiB9oec9pmbTThvCLFqBPcLSaQGjB --quantity=0 --asset TESTINGSTUFF --description="test" --divisible
[ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-cli", line 9, in <module>
    load_entry_point('counterparty-cli==1.0.0', 'console_scripts', 'counterparty-client')()
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterparty_cli-1.0.0-py3.4.egg/counterpartycli/__init__.py", line 12, in client_main
    client.main()
  File "/home/xcp/federatednode_build/env/lib/python3.4/site-packages/counterparty_cli-1.0.0-py3.4.egg/counterpartycli/client.py", line 727, in main
    quantity = util.value_in(args.quantity, None, divisible=args.divisible)
TypeError: value_in() got an unexpected keyword argument 'divisible'

**Comment by adamkrellenstein** [comment]
This issue was fixed in `develop` with https://github.com/CounterpartyXCP/counterparty-cli/commit/54776491c12c01a786a3187e822efd288c52c0f7

**Comment by ouziel-slama** [comment]
yes, I confirm, I recheck with the latest client and server version, and works well (except the double logging)

**Comment by rippler** [comment]
Because of a 404/dead link issue in the current `develop` code (Ouziel is looking into that) we cannot verify that, but we can close this now and reopen later if necessary.
