### ISSUE TITLE
getrows filter doesn't seem to work with broadcast table

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterparty-cli#36]
I built `server` and `client` from develop.
Then I tried the filtering with `getrows` filters from https://github.com/CounterpartyXCP/counterparty-cli/commit/55ea56adb6500222fad841732c3fe56c0d356ce4

```
counterparty-client.exe --testnet getrows --table broadcasts --filter 'address' '=' 'mmo6v1Mbs4gwRBkYBTa2dua9k1Ke8aRzGi'

[INFO] Running v1.0.0 of counterparty-client.
Unhandled Exception
Traceback (most recent call last):
  File "c:\Python34\Scripts\counterparty-client-script.py", line 9, in <module>
    load_entry_point('counterparty-cli==1.0.0', 'console_scripts', 'counterparty-client')()
  File "C:\Python34\lib\site-packages\counterpartycli\__init__.py", line 12, in client_main
    client.main()
  File "C:\Python34\lib\site-packages\counterpartycli\client.py", line 255, in main
    view = console.get_view(args.action, args)
  File "C:\Python34\lib\site-packages\counterpartycli\console.py", line 34, in get_view
    return util.api(method, params)
  File "C:\Python34\lib\site-packages\counterpartycli\util.py", line 95, in api
    return rpc(config.COUNTERPARTY_RPC, method, params=params, ssl_verify=config.COUNTERPARTY_RPC_SSL_VERIFY)
  File "C:\Python34\lib\site-packages\counterpartycli\util.py", line 92, in rpc
    raise RPCError('{}'.format(response_json['error']))
counterpartycli.util.RPCError: {'message': 'Server error', 'code': -32000, 'data': {'type': 'APIError', 'args': ["Invalid operator for the field ''address''"], 'message': "Invalid operator for the field ''address''"}}
```

Is this the correct syntax?
I tried '==' as well as `source` instead of `address`.

**Comment by ouziel-slama** [comment]
@rippler, there isn't `address` field in the `broadcasts` table. Use instead `source`:

`counterparty-client --testnet --verbose getrows --table broadcasts --filter 'source' '=' 'mmo6v1Mbs4gwRBkYBTa2dua9k1Ke8aRzGi'`

**Comment by rippler** [comment]
Hmm... I mentioned above, neither `source` nor `address` worked. Maybe it's a Windows apostrophe problem. I'll try on Linux.

**Comment by ouziel-slama** [comment]
yeah, I tried the exact command line in linux and macos and works well in both.

**Comment by rippler** [comment]
OK. Just for the record:

```
C:\Windows\System32>counterparty-client --config-file c:\blockchain\counterparty-client.conf 
--verbose getrows --table broadcasts --filter 'source' '=' '1C1mn9nRS7dPAgLwWnCFDmBcEx6Bimihjq'
[INFO] Running v1.1.0 of counterparty-client.←[0m
Unhandled Exception
Traceback (most recent call last):
  File "C:\Python34\Scripts\counterparty-client-script.py", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.0', 'console_scripts', 'counterparty-client')()
  File "C:\Python34\lib\site-packages\counterpartycli\__init__.py", line 12, in client_main
    client.main()
  File "C:\Python34\lib\site-packages\counterpartycli\client.py", line 257, in main
    view = console.get_view(args.action, args)
  File "C:\Python34\lib\site-packages\counterpartycli\console.py", line 34, in get_view
    return util.api(method, params)
  File "C:\Python34\lib\site-packages\counterpartycli\util.py", line 92, in api
    return rpc(config.COUNTERPARTY_RPC, method, params=params, ssl_verify=config.COUNTERPARTY_RPC_SSL_VERIFY)
  File "C:\Python34\lib\site-packages\counterpartycli\util.py", line 89, in rpc
    raise RPCError('{}'.format(response_json['error']))
counterpartycli.util.RPCError: {'message': 'Server error', 'data': {'type': 'APIError', 'message': "Invalid operator for the field ''source''", 'args'
: ["Invalid operator for the field ''source''"]}, 'code': -32000}
```
