### ISSUE TITLE
unsupported operand type(s) for -: 'int' and 'function'

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterparty-cli#4]
This was initially created (and fixed) here (https://github.com/CounterpartyXCP/counterpartyd/issues/591), but I just spotted it again, so instead of reopening it in the wrong repo, I'm creating a new issue here. This is on `develop` branches of `counterpartyd` and `counterpartyd_build`.

```
counterparty-cli.py --config-file c:\bitcoin-core-0.10\TESTNET.counterpartyd.conf --data-dir c:\bitcoin-core-0.10\counterparty-testnet market
Your Pending Order Matches
+------------------+-----------+
....

Traceback (most recent call last):
  File "c:\counterpartyd_build\dist\counterpartyd\counterparty-cli.py", line 1078, in <module>
    market(args.give_asset, args.get_asset)
  File "c:\counterpartyd_build\dist\counterpartyd\counterparty-cli.py", line 134, in market
    bet = format_bet(bet)
  File "c:\counterpartyd_build\dist\counterpartyd\counterparty-cli.py", line 81, in format_bet
    return [util.BET_TYPE_NAME[bet['bet_type']], bet['feed_address'], util.isodt(bet['deadline']), target_value, leverage, str(bet['wager_remaining']
/ config.UNIT) + ' XCP', util.value_out(db, odds, 'odds'), bet['expire_index'] - util.last_block(db)['block_index'], bet['tx_hash']]
AttributeError: 'module' object has no attribute 'isodt'
```

**Comment by rippler** [comment]
I see it's fixed in `develop`... I pulled the current code from `master` because of the testnet bug...

**Comment by rippler** [comment]
I installed `develop` and now I get a different error so I'll reopen and change Subject.

```
←[31m[ERROR] Unhandled Exception←[0m
Traceback (most recent call last):
  File "c:\counterpartyd_build\dist\counterpartyd\counterparty-cli.py", line 1106, in <module>
    market(args.give_asset, args.get_asset)
  File "c:\counterpartyd_build\dist\counterpartyd\counterparty-cli.py", line 158, in market
    bet = format_bet(bet)
  File "c:\counterpartyd_build\dist\counterpartyd\counterparty-cli.py", line 105, in format_bet
    return [util.BET_TYPE_NAME[bet['bet_type']], bet['feed_address'], log.isodt(bet['deadline']), target_value, leverage, str(bet['wager_remaining'] /
 config.UNIT) + ' XCP', util.value_out(db, odds, 'odds'), bet['expire_index'] - last_db_block_index, bet['tx_hash']]
TypeError: unsupported operand type(s) for -: 'int' and 'function'←[0m

```

**Comment by ouziel-slama** [comment]
fixed
