### ISSUE TITLE
counterparty-server: permission denied on Windows

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterparty-cli#40]
With v 1.1.0:

```[INFO] Running v1.1.0 of counterparty-server.←[0m
Traceback (most recent call last):
  File "C:\Python34\Scripts\counterparty-server-script.py", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.0', 'console_scripts', 'counterparty-server')()
  File "C:\Python34\lib\site-packages\counterpartycli\__init__.py", line 16, in server_main
    server.main()
  File "C:\Python34\lib\site-packages\counterpartycli\server.py", line 110, in main
    force=args.force, verbose=args.verbose)
  File "C:\Python34\lib\site-packages\counterpartylib\server.py", line 137, in initialise
    log.set_up(root_logger, verbose=verbose, logfile=config.LOG)
  File "C:\Python34\lib\site-packages\counterpartylib\lib\log.py", line 36, in set_up
    fileh = util_windows.SanitizedRotatingFileHandler(logfile, maxBytes=max_log_size, backupCount=5)
  File "C:\Python34\lib\logging\handlers.py", line 150, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "C:\Python34\lib\logging\handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "C:\Python34\lib\logging\__init__.py", line 1006, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Python34\lib\logging\__init__.py", line 1030, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: 'C:\\blockchain'
```

Cause?

` --log-file LOG_FILE   the path to the server log file`

When this is set to a directory path (instead of file), counterparty-server attempts to treat that directory as file, which fails.

**Comment by unsystemizer** [comment]
When installing to a non-default location, it is the user's responsibility to work out OS issues such as permissions. We can close this.
