### ISSUE TITLE
burn doesn't work properly

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterparty-cli#41]
I got 0.099 BTC on this testnet address:

```
$ counterparty-client --config-file /home/xcp/.config/counterparty/client.conf --testnet burn --source mt9WRXRphy3yDx1rg6XMV8Y7DtMHxqtZy2 --quantity 0.01
[INFO] Running v1.1.0 of counterparty-client.
[INFO] Transaction (unsigned): 01000000015c44f2fe3cec961f43e5697baaa6f69e10be1629fc93c1af44568a9c2789eb9b000000001976a9148a8b4dc6e22f1f577ae648891c1e4c274e8cb3c488acffffffff0240420f00000000001976a914a11b66a67b3ff69671c8f82254099faf374b800e88ac303bb007000000001976a9148a8b4dc6e22f1f577ae648891c1e4c274e8cb3c488ac00000000
Sign and broadcast? (y/N) y
[INFO] Transaction (signed): 01000000015c44f2fe3cec961f43e5697baaa6f69e10be1629fc93c1af44568a9c2789eb9b000000006b483045022100bd1b94dc3d76dbacc550f3ad25ce5f1474fd7d306be9bd9329cf7869da5d5bc8022050cebad6a1a12cd22f9814eca265988031d5bb29d4846638fcb688320d34f309012102762a86fa9404ff35bf1c45b4df00ac94f296b6594a2b06b6bd74c87ec7f39d36ffffffff0240420f00000000001976a914a11b66a67b3ff69671c8f82254099faf374b800e88ac303bb007000000001976a9148a8b4dc6e22f1f577ae648891c1e4c274e8cb3c488ac00000000
ERROR:root:Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-client", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.0', 'console_scripts', 'counterparty-client')()
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/__init__.py", line 12, in client_main
    client.main()
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/client.py", line 251, in main
    tx_hash = wallet.send_raw_transaction(signed_tx_hex)
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/wallet/__init__.py", line 81, in send_raw_transaction
    return WALLET().send_raw_transaction(tx_hex)
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/wallet/bitcoincore.py", line 65, in send_raw_transaction
    return rpc('sendrawtransaction', [tx_hex])
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/util.py", line 95, in wallet_api
    return rpc(config.WALLET_URL, method, params=params, ssl_verify=config.WALLET_SSL_VERIFY)
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/util.py", line 89, in rpc
    raise RPCError('{}'.format(response_json['error']))
counterpartycli.util.RPCError: {'code': -25, 'message': ''}
```

**Comment by unsystemizer** [comment]
This works fine, I just tried, let's close this.
