### ISSUE TITLE
Broadcast command is broken

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterparty-cli#43]
Current version, both Linux and Windows.
```
$ counterparty-client --config-file .config/counterparty/client.testnet.conf broadcast \
--text TEST --value 1 --source n3PUj39dhkt65iYwq4QSnMY8ajsBEnNQSP

[INFO] Running v1.1.0 of counterparty-client.
ERROR:root:Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-client", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.0', 'console_scripts', 'counterparty-client')()
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/__init__.py", line 12, in client_main
    client.main()
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/client.py", line 230, in main
    unsigned_hex = messages.compose(args.action, args)
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/messages.py", line 272, in compose
    return compose_transaction(args, message, param_names)
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/messages.py", line 263, in compose_transaction
    unsigned_tx_hex = util.api(method, params)
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/util.py", line 92, in api
    return rpc(config.COUNTERPARTY_RPC, method, params=params, ssl_verify=config.COUNTERPARTY_RPC_SSL_VERIFY)
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/util.py", line 89, in rpc
    raise RPCError('{}'.format(response_json['error']))
counterpartycli.util.RPCError: {'code': -32000, 'message': 'Server error', 'data': {'message': 'unorderable types: NoneType() < int()', 'type': 'APIError', 'args': ['unorderable types: NoneType() < int()']}}
```

**Comment by adamkrellenstein** [comment]
Solved: 150d24c21fa80bfd3295916aa54bc061311171d9
