### ISSUE TITLE
`wallet` command doesn't display all assets

### ISSUE THREAD

**Issue by atweiden** [CounterpartyXCP/counterparty-cli#46]
On testnet, after burning all available BTC at `n1LFjn1JVeoSgopz4bhvnb3tS4bjZmgwQK`, the `counterparty-client wallet` cmd did not display unnamed assets `A1111111111111111111` or `A2222222222222222222`.

https://testnet.blockscan.com/address/n1LFjn1JVeoSgopz4bhvnb3tS4bjZmgwQK

Since the `wallet` cmd still did not display XCP or A111 or A222 balances after 5 confirmations, I tried running the `balances` cmd:

```
counterparty-client --config-file ~/.config/counterparty/client.testnet.conf balances n1LFjn1JVeoSgopz4bhvnb3tS4bjZmgwQK
[INFO] Running v1.1.1 of counterparty-client.
Unhandled Exception
Traceback (most recent call last):
  File "/bin/counterparty-client", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.1', 'console_scripts', 'counterparty-client')()
  File "/usr/lib/python3.4/site-packages/counterpartycli/__init__.py", line 12, in client_main
    client.main()
  File "/usr/lib/python3.4/site-packages/counterpartycli/client.py", line 257, in main
    view = console.get_view(args.action, args)
  File "/usr/lib/python3.4/site-packages/counterpartycli/console.py", line 8, in get_view
    return wallet.balances(args.address)
  File "/usr/lib/python3.4/site-packages/counterpartycli/wallet/__init__.py", line 198, in balances
    'BTC': get_btc_balance(address)
  File "/usr/lib/python3.4/site-packages/counterpartycli/wallet/__init__.py", line 75, in get_btc_balance
    return WALLET().get_btc_balance(address)
  File "/usr/lib/python3.4/site-packages/counterpartycli/wallet/btcwallet.py", line 57, in get_btc_balance
    if output['address'] == addresses:
NameError: name 'addresses' is not defined
```

**Comment by ouziel-slama** [comment]
Fixed here: https://github.com/CounterpartyXCP/counterparty-cli/commit/dce6ab93725b7483cf7796923ca78471a0b17b36

**Comment by ouziel-slama** [comment]
I reopened the issue and changed the title.

**Comment by atweiden** [comment]
Fixing the balance cmd fixed the wallet cmd.

**Comment by ouziel-slama** [comment]
great! thanks for the feedback.
