### ISSUE TITLE
NameError: name 'source' is not defined

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterparty-cli#5]
v9.49.3 (`master`) on Windows:

```
C:\bitcoin-core-0.10>c:\python34\python.exe c:\counterpartyd_build\dist\counterpartyd\counterparty-cli.py --data-dir c:\bitcoin-core-0.10\counterparty --testnet --config-file c:\bitcoin-core-0.10\TESTNET.counterpartyd.conf --testnet broadcast --text "Source is defined 1=Y,2=N" --value 1 --source myG2jGS146LntchbNHaAHqPZJyqwqdorUX --fee-fraction 0.005
Transaction (unsigned): 0100000005ddb9d0224a344f15cab63c9efa19b1216d57c0f39c00bd31cdbdd47dbf7cab68000000001976a914c29fba0187fc7070b58247244cecf503ee0a67fb88acffffffff8979e521cdffb6bcff70fbb19a7e48caa5c8ec487a733d7c297391b346a4d293000000001976a914c29fba0187fc7070b58247244cecf503ee0a67fb88acffffffff64fb70adb5e72c791bf78e6312b3e6846bf67c1363290e27ed94b7453fad59cb000000001976a914c29fba0187fc7070b58247244cecf503ee0a67fb88acffffffff7330166630dfa9de6d8c42784165ce58be5c799b2c229cc179ef7a9cff7613d1000000001976a914c29fba0187fc7070b58247244cecf503ee0a67fb88acffffffff72a8ed7a6a4f1def6f49c5786a494f0aa0bf5b2681005068cb447463988f2ad2020000001976a914c29fba0187fc7070b58247244cecf503ee0a67fb88acffffffff02771e000000000000695121023f26f66bbdfde326445a420083656d290c42ce4aa44b5408d3e89c769740e54f21030b95330dd051f58d36cc915e2ed565f61d48f9bf44f710877dd2ae11c79439c0210376156a1397b2f282c8f18bda70e09b5fa1bd9cd6b159c11ba661d68ec11a288853ae8f941c00000000001976a914c29fba0187fc7070b58247244cecf503ee0a67fb88ac00000000
Sign and broadcast? (y/N) y
Traceback (most recent call last):
  File "c:\counterpartyd_build\dist\counterpartyd\counterparty-cli.py", line 832, in <module>
    args.unsigned)
  File "c:\counterpartyd_build\dist\counterpartyd\counterparty-cli.py", line 223, in cli
    if backend.is_mine(proxy, source):
NameError: name 'source' is not defined
```

**Comment by ouziel-slama** [comment]
fixed
