### ISSUE TITLE
counterparty-cli fails to install via pip3 (addrindex.py part)

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-cli#56]
* Updated Ubuntu 14.04 
* `sudo pip3 install counterparty-cli`

```
    Installing counterparty-client script to /usr/local/bin
    writing list of installed files to '/tmp/pip-aon_8hyr-record/install-record.txt'
    running generate_configuration_files
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kgvhjjbh/counterparty-cli/setup.py", line 126, in <module>
        setup(**setup_options)
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-kgvhjjbh/counterparty-cli/setup.py", line 34, in run
        self.run_command('generate_configuration_files')
      File "/usr/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-kgvhjjbh/counterparty-cli/setup.py", line 21, in run
        generate_config_files()
      File "/tmp/pip-build-kgvhjjbh/counterparty-cli/counterpartycli/setup.py", line 142, in generate_config_files
        from counterpartycli.server import CONFIG_ARGS as SERVER_CONFIG_ARGS
      File "/tmp/pip-build-kgvhjjbh/counterparty-cli/counterpartycli/server.py", line 11, in <module>
        from counterpartylib import server
      File "/usr/local/lib/python3.4/dist-packages/counterpartylib/server.py", line 19, in <module>
        from counterpartylib.lib import api, config, util, exceptions, blocks, check, backend, database, transaction, script, log
      File "/usr/local/lib/python3.4/dist-packages/counterpartylib/lib/api.py", line 39, in <module>
        from counterpartylib.lib import check
      File "/usr/local/lib/python3.4/dist-packages/counterpartylib/lib/check.py", line 12, in <module>
        from counterpartylib.lib import backend
      File "/usr/local/lib/python3.4/dist-packages/counterpartylib/lib/backend/__init__.py", line 18, in <module>
        from counterpartylib.lib.backend import addrindex, btcd
      File "/usr/local/lib/python3.4/dist-packages/counterpartylib/lib/backend/addrindex.py", line 6, in <module>
        from requests.exceptions import Timeout, ReadTimeout, ConnectionError
    ImportError: cannot import name 'ReadTimeout'

    ----------------------------------------
Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-kgvhjjbh/counterparty-cli/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-aon_8hyr-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-kgvhjjbh/counterparty-cli
```

Maybe related to #55 or pip3 (after #55 I upgraded pip3 to 7.1.0)

```
user@ubuntu:~$ sudo pip3 list
appdirs (1.4.0)
apsw (3.8.7.3.post1)
chardet (2.2.1)
colorama (0.2.5)
colorlog (2.6.0)
command-not-found (0.3)
counterparty-cli (1.1.1)
counterparty-lib (9.51.3)
coverage (3.7.1)
Flask (0.10.1)
Flask-HTTPAuth (2.5.0)
html5lib (0.999)
itsdangerous (0.24)
Jinja2 (2.8)
json-rpc (1.10.1)
language-selector (0.1)
MarkupSafe (0.23)
pip (7.1.0)
prettytable (0.7.2)
py (1.4.30)
pycoin (0.52)
pycrypto (2.6.1)
pygobject (3.12.0)
pysha3 (0.3)
pytest (2.7.2)
pytest-cov (2.0.0)
python-apt (0.9.3.5ubuntu1)
python-bitcoinlib (0.4.0)
python-dateutil (2.4.2)
requests (2.7.0)
setuptools (3.3)
six (1.9.0)
tendo (0.2.8)
tornado (4.2.1)
ufw (0.34-rc-0ubuntu2)
urllib3 (1.7.1)
Werkzeug (0.10.4)
wheel (0.24.0)
xmltodict (0.9.2)
user@ubuntu:~$ sudo pip3 -V
pip 7.1.0 from /usr/local/lib/python3.4/dist-packages (python 3.4)
```

**Comment by unsystemizer** [comment]
Closing because I couldn't repro using the built in pip3.
