### ISSUE TITLE
Errors when starting counterparty-client on Windows

### ISSUE THREAD

**Issue by Millz0r** [CounterpartyXCP/counterparty-cli#6]
Getting this error when trying the new Windows package:
```
C:\Users\millz\Desktop\coutnerwallet\counterparty-cli-win32-1.0.0>counterparty-client.exe
Traceback (most recent call last):
  File "counterparty-client", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\counterparty\counterparty-cli\counterpartycli\client.py", line 27, in
 <module>
  File "C:\Users\millz\Desktop\coutnerwallet\counterparty-cli-win32-1.0.0\librar
y\counterparty\lib\util_windows.py", line 10, in <module>
    class SanitizedRotatingFileHandler(logging.handlers.RotatingFileHandler):
AttributeError: 'module' object has no attribute 'handlers'
```
Here's the configuration file:
```
C:\Users\millz\AppData\Roaming\counterparty-client\counterparty-client.conf:
[Default]
wallet-name = bitcoincore
wallet-connect = localhost
wallet-user = rpcuser
wallet-password = password
counterparty-rpc-host = localhost
counterparty-rpc-user = rpcuser
counterparty-rpc-password = password
```

**Comment by robby-dermody** [comment]
looks like py2exe is not freezing logging.handlers. the py2exe config will need to be updated to explicitly include these modules in the frozen output.

@ouziel-slama I'm not sure how this is done with setup.py based installs, but let me know if you're having issues with it and I can see if I can help out

**Comment by ouziel-slama** [comment]
thank you @robby-dermody! I fixed that here: https://github.com/CounterpartyXCP/counterpartyd/commit/cd94d9bbe085def5044e6351d2bb8b9433b3031c
I have to do some modifications and I will build an RC2.
