### ISSUE TITLE
messages.py (L169) NameError: name 'calendar' is not defined

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-cli#62]
```
$ counterparty-client bet --source ADD1 --feed-address ADD2 --wager 0.05 --counterwager 0.06 --expiration 20 --bet-type Equal --deadline 2015-11-01T05:06:07+00:00
[INFO] Running v1.1.1 of counterparty-client.
Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-client", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.1', 'console_scripts', 'counterparty-client')()
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/__init__.py", line 12, in client_main
    client.main()
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/client.py", line 230, in main
    unsigned_hex = messages.compose(args.action, args)
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/messages.py", line 274, in compose
    return compose_transaction(args, message, param_names)
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/messages.py", line 250, in compose_transaction
    args = prepare_args(args, message_name)
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/messages.py", line 169, in prepare_args
    args.deadline = calendar.timegm(dateutil.parser.parse(args.deadline).utctimetuple())
NameError: name 'calendar' is not defined
```

**Comment by unsystemizer** [comment]
@ouziel-slama can you take a look?
I'm getting errors in CW as well ("Counterwallet could not find Enhanced Feed Information at this address") and now I'm thinking maybe this is what's preventing CW from parsing the feed. 
I can't tell for sure, but if I could use the CLI at least I could see whether betting and resolution works fine, but this is blocking me.

**Comment by unsystemizer** [comment]
@robby-dermody is this something that can be fixed in next version? It seems relatively straightforward.
