### ISSUE TITLE
AttributeError: 'WSGIRequestHandler' object has no attribute 'environ'

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-cli#70]
```
$ counterparty-client --version
counterparty-client v1.1.1; counterparty-lib v9.53.0
```

When I issue `counterparty-client asset XCP` I get this:

```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 41642)
Traceback (most recent call last):
  File "/usr/lib/python3.4/socketserver.py", line 617, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.4/socketserver.py", line 344, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.4/socketserver.py", line 673, in __init__
    self.handle()
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/serving.py", line 217, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.4/http/server.py", line 401, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/serving.py", line 251, in handle_one_request
    elif self.parse_request():
  File "/usr/lib/python3.4/http/server.py", line 317, in parse_request
    self.send_error(400, "Bad request syntax (%r)" % requestline)
  File "/usr/lib/python3.4/http/server.py", line 431, in send_error
    self.log_error("code %d, message %s", code, message)
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/serving.py", line 273, in log_error
    self.log('error', *args)
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/serving.py", line 279, in log
    _log(type, '%s - - [%s] %s\n' % (self.address_string(),
  File "/usr/local/lib/python3.4/dist-packages/werkzeug/serving.py", line 267, in address_string
    return self.environ['REMOTE_ADDR']
AttributeError: 'WSGIRequestHandler' object has no attribute 'environ'
----------------------------------------
```

Known upstream issue, waiting for them to merge it: https://github.com/mitsuhiko/werkzeug/pull/838

**Comment by unsystemizer** [comment]
Upstream issue closed and I haven't seen this in our s/w, so closing
