### ISSUE TITLE
Stateless RPC connection: tolerate backend service restart/downtime

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-cli#77]
Currently counterparty-server can't recover from Bitcoin Core service restart even if it's immediate. 

```
2016-05-20-T09:42:00+0100 [ERROR] Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.1', 'console_scripts', 'counterparty-server')()
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/__init__.py", line 16, in server_main
    server.main()
  File "/usr/local/lib/python3.4/dist-packages/counterpartycli/server.py", line 135, in main
    server.start_all(db)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.54.0-py3.4.egg/counterpartylib/server.py", line 372, in start_all
    blocks.follow(db)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.54.0-py3.4.egg/counterpartylib/lib/blocks.py", line 1145, in follow
    tx_index = list_tx(db, block_hash, block_index, block_time, tx_hash, tx_index, tx_hex)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.54.0-py3.4.egg/counterpartylib/lib/blocks.py", line 845, in list_tx
    source, destination, btc_amount, fee, data = get_tx_info(tx_hex)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.54.0-py3.4.egg/counterpartylib/lib/blocks.py", line 424, in get_tx_info
    tx_info = get_tx_info2(tx_hex, block_parser=block_parser)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.54.0-py3.4.egg/counterpartylib/lib/blocks.py", line 665, in get_tx_info2
    vin_tx = backend.getrawtransaction(ib2h(vin.prevout.hash))
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.54.0-py3.4.egg/counterpartylib/lib/backend/__init__.py", line 55, in getrawtransaction
    return BACKEND().getrawtransaction(tx_hash, verbose=verbose, skip_missing=skip_missing)
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.54.0-py3.4.egg/counterpartylib/lib/backend/addrindex.py", line 230, in getrawtransaction
    return getrawtransaction_batch([tx_hash], verbose=verbose, skip_missing=skip_missing)[tx_hash]
  File "/usr/local/lib/python3.4/dist-packages/counterparty_lib-9.54.0-py3.4.egg/counterpartylib/lib/backend/addrindex.py", line 291, in getrawtransaction_batch
    raise BackendRPCError('{} (txhash:: {})'.format(response['error'], tx_hash_call_id.get(response.get('id', '??'), '??')))
counterpartylib.lib.backend.addrindex.BackendRPCError: {'message': 'Loading block index...', 'code': -28} (txhash:: 633077620cae25bc0cbcbf35545d9ca3c91b338112bc7364e1bf2d5a5d8022bd)
```
(crash)

This is a problem when one has to restart bitcoind (upgrade, migration, change of settings, extended loss of connectivity due to overload, Bitcoin Core crash, etc.).

If zero-conf tx parsing (see https://github.com/CounterpartyXCP/counterparty-lib/pull/869) could be disabled perhaps this connection could be "stateless" which would be a reliability improvement for services that do not depend on zero-conf transactions (which could be useful to CP EVM users where uptime is important while zero-conf may not be?).
It would also be possible to use a floating IP to run 2 or more BC instances with 1 virtual IP and move the IP to another instance and thereby insure smooth backend failover.

**Comment by robby-dermody** [comment]
Can you please close and reopen this on Counterparty-lib's repo, since it's an issue there?

**Comment by unsystemizer** [comment]
OK

**Comment by robby-dermody** [comment]
It appears to be a valid issue though.
