### ISSUE TITLE
py2exe: counterparty-cli-win32-1.0.0 cannot be found

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterparty-cli#8]
Downloaded zip archive from `develop`, unzipped and tried to build the executable from a console with Admin privileges.
```
C:\Python34\counterparty-cli-develop\counterparty-cli-develop>..\..\python.exe s
etup.py py2exe
Traceback (most recent call last):
  File "setup.py", line 56, in <module>
    shutil.rmtree(WIN_DIST_DIR)
  File "C:\Python34\lib\shutil.py", line 477, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Python34\lib\shutil.py", line 359, in _rmtree_unsafe
    onerror(os.listdir, path, sys.exc_info())
  File "C:\Python34\lib\shutil.py", line 357, in _rmtree_unsafe
    names = os.listdir(path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'coun
terparty-cli-win32-1.0.0'
```

**Comment by adamkrellenstein** [comment]
Try again with the latest pip packages.

**Comment by rippler** [comment]
* Upgraded the both modules with `pip`. `counterparty-cli --help` now produces correct output.
* counterparty-cli (1.0.0)
* counterparty-lib (9.49.4)
* As reported earlier this week, the Windows build still needs the `.py` extension or else must be executed by passing the script name to `python.exe`.


* Btw, if I download the zip archive `python.exe setup.py py2exe` goes further 
```
C:\Python34\counterparty-cli-develop\counterparty-cli-develop>..\..\python.exe s
etup.py py2exe
running py2exe
running build_py
creating build
creating build\lib
creating build\lib\counterpartycli
copying counterpartycli\client.py -> build\lib\counterpartycli
copying counterpartycli\server.py -> build\lib\counterpartycli
copying counterpartycli\util.py -> build\lib\counterpartycli
copying counterpartycli\__init__.py -> build\lib\counterpartycli
creating build\lib\counterpartycli\wallet
copying counterpartycli\wallet\bitcoincore.py -> build\lib\counterpartycli\walle
t
copying counterpartycli\wallet\__init__.py -> build\lib\counterpartycli\wallet
running build_scripts
creating build\scripts-3.4
copying and adjusting bin\counterparty-client -> build\scripts-3.4
copying and adjusting bin\counterparty-server -> build\scripts-3.4

  33 missing Modules
  ------------------
? Cookie                              imported from requests.compat, tornado.htt
putil, tornado.web
? HTMLParser                          imported from prettytable
? OpenSSL                             imported from requests.packages.urllib3.co
ntrib.pyopenssl, werkzeug.serving
? Queue                               imported from requests.packages.urllib3.co
nnectionpool
? SocketServer                        imported from werkzeug.serving
? UserDict                            imported from jinja2._compat
? __pypy__                            imported from jinja2.debug
? _abcoll                             imported from requests.packages.urllib3.pa
ckages.ordered_dict
? backports                           imported from requests.packages.urllib3.pa
ckages.ssl_match_hostname, tornado.netutil
? blinker                             imported from flask.signals
? com                                 imported from appdirs
? cookielib                           imported from requests.compat, werkzeug.te
st
? email.Utils                         imported from werkzeug.http
? flask.ext.httpauth                  imported from counterpartylib.lib.api
? greenlet                            imported from werkzeug.local
? jinja2.debugrenderer                imported from jinja2.debug
? monotime                            imported from tornado.platform.auto
? multiprocessing.SimpleQueue         imported from concurrent.futures.process
? ndg                                 imported from requests.packages.urllib3.co
ntrib.pyopenssl
? plyvel                              imported from counterpartylib.lib.kickstar
t.blocks_parser
? pretty                              imported from jinja2.utils
? pyasn1                              imported from requests.packages.urllib3.co
ntrib.pyopenssl
? pyinotify                           imported from werkzeug.serving
? readline                            imported from cmd, code, pdb
? sets                                imported from pkg_resources
? simplejson                          imported from itsdangerous, requests.compa
t
? urllib.getproxies                   imported from requests.compat
? urllib.proxy_bypass                 imported from requests.compat
? urllib.quote                        imported from jinja2._compat, requests.com
pat
? urllib.quote_plus                   imported from requests.compat
? urllib.unquote                      imported from requests.compat
? urllib.unquote_plus                 imported from requests.compat
? urllib.urlencode                    imported from requests.compat, requests.pa
ckages.urllib3.request, tornado.httputil, tornado.web
Building 'counterparty-cli-win32-1.0.0\counterparty-client.exe'.
Building 'counterparty-cli-win32-1.0.0\counterparty-server.exe'.
Building shared code archive 'counterparty-cli-win32-1.0.0\library/site-packages
.zip'.
Copy c:\python34\python34.dll to counterparty-cli-win32-1.0.0
Copy C:\Python34\DLLs\unicodedata.pyd to counterparty-cli-win32-1.0.0\library\un
icodedata.pyd
Copy C:\Python34\lib\site-packages\win32\win32wnet.pyd to counterparty-cli-win32
-1.0.0\library\win32wnet.pyd
Copy C:\Python34\DLLs\_ctypes.pyd to counterparty-cli-win32-1.0.0\library\_ctype
s.pyd
Copy C:\Python34\lib\site-packages\Crypto\Cipher\_ARC4.pyd to counterparty-cli-w
in32-1.0.0\library\Crypto.Cipher._ARC4.pyd
Copy C:\Python34\DLLs\_hashlib.pyd to counterparty-cli-win32-1.0.0\library\_hash
lib.pyd
Copy C:\Python34\DLLs\_ssl.pyd to counterparty-cli-win32-1.0.0\library\_ssl.pyd
Copy C:\Python34\lib\site-packages\apsw.pyd to counterparty-cli-win32-1.0.0\libr
ary\apsw.pyd
Copy C:\Python34\lib\site-packages\markupsafe\_speedups.pyd to counterparty-cli-
win32-1.0.0\library\markupsafe._speedups.pyd
Copy C:\Python34\lib\site-packages\win32\win32evtlog.pyd to counterparty-cli-win
32-1.0.0\library\win32evtlog.pyd
Copy C:\Python34\lib\site-packages\win32comext\shell\shell.pyd to counterparty-c
li-win32-1.0.0\library\win32com.shell.shell.pyd
Copy C:\Python34\lib\site-packages\Crypto\Hash\_RIPEMD160.pyd to counterparty-cl
i-win32-1.0.0\library\Crypto.Hash._RIPEMD160.pyd
Copy C:\Python34\lib\site-packages\win32\_win32sysloader.pyd to counterparty-cli
-win32-1.0.0\library\_win32sysloader.pyd
Copy C:\Python34\DLLs\_multiprocessing.pyd to counterparty-cli-win32-1.0.0\libra
ry\_multiprocessing.pyd
Copy C:\Python34\DLLs\_socket.pyd to counterparty-cli-win32-1.0.0\library\_socke
t.pyd
Copy C:\Python34\lib\site-packages\tornado\speedups.pyd to counterparty-cli-win3
2-1.0.0\library\tornado.speedups.pyd
Copy C:\Python34\lib\site-packages\win32\win32api.pyd to counterparty-cli-win32-
1.0.0\library\win32api.pyd
Copy C:\Python34\DLLs\select.pyd to counterparty-cli-win32-1.0.0\library\select.
pyd
Copy C:\Python34\DLLs\_bz2.pyd to counterparty-cli-win32-1.0.0\library\_bz2.pyd
Copy C:\Python34\lib\site-packages\_sha3.pyd to counterparty-cli-win32-1.0.0\lib
rary\_sha3.pyd
Copy C:\Python34\DLLs\pyexpat.pyd to counterparty-cli-win32-1.0.0\library\pyexpa
t.pyd
Copy C:\Python34\DLLs\_decimal.pyd to counterparty-cli-win32-1.0.0\library\_deci
mal.pyd
Copy C:\Python34\DLLs\_lzma.pyd to counterparty-cli-win32-1.0.0\library\_lzma.py
d
Copy DLL C:\Python34\MSVCR100.dll to counterparty-cli-win32-1.0.0\library
Copy ExtensionDLL C:\Python34\pywintypes34.dll to counterparty-cli-win32-1.0.0\l
ibrary
Copy ExtensionDLL C:\Python34\pythoncom34.dll to counterparty-cli-win32-1.0.0\li
brary
```

**Comment by ouziel-slama** [comment]
@sean:
- I try to find a solution for the `.py` extension in Windows
- You can not run `py2exe` without having already a complete configuration. That means, you need to install manually `apsw`, `openssl`, etc.. before you can run `py2exe`.

**Comment by rippler** [comment]
Sounds good. I remember we talked about that but then earlier today I read the doc file in which `py2exe` was mentioned so I thought that was fixed in the meantime. Maybe we should put a note in the document about this (to use pip, not py2exe).

**Comment by adamkrellenstein** [comment]
Closing, but @rippler, where should we put that note? (Make a PR,)

**Comment by rippler** [comment]
I think here could be good? 
https://github.com/CounterpartyXCP/Documentation/pull/13

**Comment by adamkrellenstein** [comment]
Merged it.
