### ISSUE TITLE
Exception: KeyError: 'sends'.  when calling asset BTC.

### ISSUE THREAD

**Issue by dan-da** [CounterpartyXCP/counterparty-cli#91]
Got this error.

```
$ counterparty-client asset BTC
[2016-08-22 10:51:07][INFO] Running v1.1.2 of counterparty-client.
Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-client", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.2', 'console_scripts', 'counterparty-client')()
  File "/home/counterpartycoin/counterparty-cli/counterpartycli/__init__.py", line 12, in client_main
    client.main()
  File "/home/counterpartycoin/counterparty-cli/counterpartycli/client.py", line 252, in main
    print_method(view)
  File "/home/counterpartycoin/counterparty-cli/counterpartycli/console.py", line 73, in print_asset
    if asset['sends']:
KeyError: 'sends'
```

I fixed (or worked around) it with:
```

diff --git a/counterpartycli/console.py b/counterpartycli/console.py
index b76b139..1cd246e 100755
--- a/counterpartycli/console.py
+++ b/counterpartycli/console.py
@@ -70,7 +70,7 @@ def print_asset(asset):
             table.add_row([address, balance])
         lines.append(table.get_string())
 
-    if asset['sends']:
+    if 'sends' in asset and asset['sends']:
         lines.append('')
         lines.append('Sends')
         table = PrettyTable(['Type', 'Quantity', 'Source', 'Destination'])
```

**Comment by unsystemizer** [comment]
Do you want submit a Pull Request for this to `develop` branch?

**Comment by unsystemizer** [comment]
* Largely duplicate of #48 
* Note that this is consistent with the API behavior - BTC is not a Counterparty asset, so transaction history is not supposed to be looked up this way. I think if you want to look up tx history, you should submit a PR for the wallet or balances function in console.py.

Can we close this now?

**Comment by dan-da** [comment]
I just submitted the issue because I thought the maintainers might like to be aware and do something about it.

Seems to me that a well designed software handling people's money should handle all user input as gracefully as possible.  If looking up BTC is not supported, then it should probably give a friendly error message in that case.

**Comment by unsystemizer** [comment]
Absolutely - thanks for taking time to let us know and share the patch. I just wanted to check if you want to submit a pull request by yourself (some people mind if others use their code to submit a pull request).

We'll try to improve console.py shortly, maybe by adding improvements to another command. 
By the way, you could probably build a shell alias to the `getrows` action (just use the sends table and filter for `BTC`).

Example for the balances table, from the CLI manual (yeah, it's a testnet address, but `--testnet` was omitted):

```
getrows --table balances --filter 'address' '=' 'muQjaj46wghHprjSjpgU7D55JxKyK5dJtZ' \
--filter 'asset' '=' 'BBBQ'
```

Maybe I'll add couple of examples about this to the CLI guide.

**Comment by dan-da** [comment]
I'm not going to submit a pull request.  I would if I'd done something significant, but that was just a one-liner that quickly resolved the issue for me, so I included it as example -- likely not the correct fix.

**Comment by unsystemizer** [comment]
For future reference:

* Here's what the patch does:

```
$ counterparty-client asset BTC
[2016-12-31 12:34:01][INFO] Running v1.1.2 of counterparty-client.

Informations
+--------------+------------+
| Asset Name:  |    BTC     |
|  Asset ID:   |     0      |
|  Divisible:  |    True    |
|   Locked:    |   False    |
|   Supply:    | 16074587.5 |
|   Issuer:    |    None    |
| Description: |     ‘’     |
|   Balance:   | 0.00972442 |
+--------------+------------+

Addresses
+------------------------------------+------------+
|              Address               |  Balance   |
+------------------------------------+------------+
| xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx | 0.01972442 |
+------------------------------------+------------+
```

(I wasn't sure whether the workaround was that with it the API returns a "not supported" message, or it actually treats BTC as another CP asset name. Interestingly the supply amount is correct too).

* In the protocol specification  [BTC sends aren't considered to be Counterparty transactions](https://github.com/CounterpartyXCP/Documentation/blob/master/Developers/protocol_specification.md#noncounterparty-transactions) and BTC isn't a CP asset, so we could adopt this patch but also create a different action that would provide similar functionality (maybe just proxy requests similar to the way `get_{table}` works, but only to Bitcoin Core).  Ideas and contributions are welcome.

**Comment by chiguireitor** [comment]
Guess the correct solution is to return a "not an asset" error (BTC is not an asset anyways)
