### ISSUE TITLE
destroy action: "method not found"

### ISSUE THREAD

**Issue by unsystemizer** [CounterpartyXCP/counterparty-cli#96]
It seems it was fixed/cleaned up in the latest update...
The command is also not well documented, but I'll think about that later.

```
$ counterparty-server --version
counterparty-server v1.1.2; counterparty-lib v9.55.0

$ counterparty-client --conf=/home/user/.config/counterparty/client.testnet.conf asset A151741440000000000
[2016-10-31 20:37:30][INFO] Running v1.1.2 of counterparty-client.

Informations
+--------------+------------------------------------+
| Asset Name:  |        A151741440000000000         |
|  Asset ID:   |         151741440000000000         |
|  Divisible:  |               False                |
|   Locked:    |               False                |
|   Supply:    |                 1                  |
|   Issuer:    | n4D7ndiC4yLZxhAf726uMHXC914sEuUAcg |
| Description: |                 ‘’                 |
|   Balance:   |                 1                  |
+--------------+------------------------------------+

Addresses
+------------------------------------+---------+
|              Address               | Balance |
+------------------------------------+---------+
| n4D7ndiC4yLZxhAf726uMHXC914sEuUAcg |    1    |
+------------------------------------+---------+

$ counterparty-client --conf=/home/user/.config/counterparty/client.testnet.conf destroy --source n4D7ndiC4yLZxhAf726uMHXC914sEuUAcg --asset A151741440000000000 --quantity 1
[2016-10-31 20:37:56][INFO] Running v1.1.2 of counterparty-client.
ERROR:root:Unhandled Exception
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-client", line 9, in <module>
    load_entry_point('counterparty-cli==1.1.2', 'console_scripts', 'counterparty-client')()
  File "/usr/local/lib/python3.5/dist-packages/counterpartycli/__init__.py", line 12, in client_main
    client.main()
  File "/usr/local/lib/python3.5/dist-packages/counterpartycli/client.py", line 220, in main
    unsigned_hex = messages.compose(args.action, args)
  File "/usr/local/lib/python3.5/dist-packages/counterpartycli/messages.py", line 278, in compose
    return compose_transaction(args, message, param_names)
  File "/usr/local/lib/python3.5/dist-packages/counterpartycli/messages.py", line 269, in compose_transaction
    unsigned_tx_hex = util.api(method, params)
  File "/usr/local/lib/python3.5/dist-packages/counterpartycli/util.py", line 92, in api
    return rpc(config.COUNTERPARTY_RPC, method, params=params, ssl_verify=config.COUNTERPARTY_RPC_SSL_VERIFY)
  File "/usr/local/lib/python3.5/dist-packages/counterpartycli/util.py", line 89, in rpc
    raise RPCError('{}'.format(response_json['error']))
counterpartycli.util.RPCError: {'message': 'Method not found', 'code': -32601}
```

**Comment by unsystemizer** [comment]
It seems this is a remnant of the old asset callback functionality that was removed a while ago.

**Comment by unsystemizer** [comment]
After some debugging of the client I think `destroy` isn't available in the API.

**Comment by unsystemizer** [comment]
Documented in the CLI guide that the command is not implemented.
